# Generated by Django 6.0.3 on 2026-05-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_appmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantreading',
            name='soil_level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4095)]),
        ),
    ]
