# Generated by Django 6.0.3 on 2026-05-23 15:43

from django.db import migrations, models


def backfill_analysis_status(apps, _schema_editor):
    PlantReading = apps.get_model('readings', 'PlantReading')
    PlantReading.objects.exclude(condition__isnull=True).exclude(condition='').update(
        analysis_status='completed'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_alter_plantreading_soil_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantreading',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantreading',
            name='analysis_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plantreading',
            name='analysis_mode',
            field=models.CharField(choices=[('sfw', 'Safe for Work'), ('nsfw', 'Not Safe for Work')], default='sfw', max_length=10),
        ),
        migrations.AddField(
            model_name='plantreading',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantreading',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.RunPython(backfill_analysis_status, migrations.RunPython.noop),
    ]
